name: CI/CD Deploy to EC2

on:
  push:
    branches: [ "release/main" ]   # "release/main" 브랜치 push 시 자동 배포

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      # 4. 첫 번째 서버 배포
#      - name: Deploy to EC2 (Server 1)
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.EC2_HOST_1 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo systemctl stop tomcat || true
#            sudo rm -rf /opt/tomcat/webapps/ROOT*
#            exit
#
#      - name: Copy WAR to Server 1
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.EC2_HOST_1 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          source: "build/libs/*.war"
#          target: "/home/ec2-user/"
#
#      - name: Restart Tomcat on Server 1
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.EC2_HOST_1 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo mv /home/ec2-user/*.war /opt/tomcat/webapps/ROOT.war
#            sudo chown root:root /opt/tomcat/webapps/ROOT.war
#            sudo chmod 644 /opt/tomcat/webapps/ROOT.war
#            sudo systemctl start tomcat
#
#      # 5. 두 번째 서버 배포 (동일 절차 반복)
#      - name: Deploy to EC2 (Server 2)
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.EC2_HOST_2 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo systemctl stop tomcat || true
#            sudo rm -rf /opt/tomcat/webapps/ROOT*
#            exit
#
#      - name: Copy WAR to Server 2
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.EC2_HOST_2 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          source: "build/libs/*.war"
#          target: "/home/ec2-user/"
#
#      - name: Restart Tomcat on Server 2
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.EC2_HOST_2 }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo mv /home/ec2-user/*.war /opt/tomcat/webapps/ROOT.war
#            sudo chown root:root /opt/tomcat/webapps/ROOT.war
#            sudo chmod 644 /opt/tomcat/webapps/ROOT.war
#            sudo systemctl start tomcat